"""Shared fixtures for the tuipet test suite.

The single most important thing this file does is **isolate persistence** so a
test can never touch Joel's real save/settings at ~/.local/share/tuipet/ (a
leaked test save has corrupted the live game before). The `isolate_save`
fixture is autouse, so every test in the suite gets a throwaway save dir.
"""
import pytest

from tuipet import persistence


@pytest.fixture(autouse=True)
def isolate_save(tmp_path, monkeypatch):
    """Redirect all persistence I/O into a per-test tmp dir.

    persistence resolves SAVE_PATH/SETTINGS_PATH at call time (`path or <GLOBAL>`),
    so monkeypatching the module globals is enough to fully sandbox it.
    """
    monkeypatch.setattr(persistence, "SAVE_DIR", str(tmp_path))
    monkeypatch.setattr(persistence, "SAVE_PATH", str(tmp_path / "save.json"))
    monkeypatch.setattr(persistence, "SETTINGS_PATH", str(tmp_path / "settings.json"))
    yield


def _by_num():
    from tuipet import data
    _, by_num = data.load_sprites()
    return by_num


def live_num(stage="Rookie"):
    """A real, non-placeholder Digimon num of the given stage, or None if assets
    aren't installed (sprites are gitignored / regenerated by setup_assets.sh)."""
    from tuipet import data
    by_num = _by_num()
    return next((n for n, r in by_num.items()
                 if r["stage"] == stage and not data.is_placeholder(n)), None)


@pytest.fixture
def live_pet():
    """A freshly-spawned Rookie from real sprite data (skips if assets missing)."""
    from tuipet.pet import Pet
    num = live_num("Rookie")
    if num is None:
        pytest.skip("sprite assets not installed (run tools/setup_assets.sh)")
    p = Pet.from_num(num)
    p.obedience = 500        # out-roll the canon item/food refusal (audit 2026-07)
    return p


def futon_item():
    """Discover the (key, entry) of an item granting a care effect (the Futon), or
    (None, None). Avoids hardcoding the item id so the test survives a data refresh."""
    from tuipet import data
    _, items = data._load_consumables()
    for cid, e in items.items():
        if e.get("effect_id", -1) >= 0:
            return f"i:{cid}", e
    return None, None


@pytest.fixture(autouse=True)
def _sandbox_lobby_feed(tmp_path, monkeypatch):
    """The lobby server module logs public events to FEED_PATH on login/chat/
    disconnect -- any test driving server flows must write a scratch feed, or
    pytest runs append real-looking events to the repo copy (leak found
    2026-07-10: test_bugreport/test_save_integrity grew server/lobby_feed.jsonl
    on every run)."""
    import sys as _sys
    srv = _sys.modules.get("server")
    if srv is not None and hasattr(srv, "FEED_PATH"):
        monkeypatch.setattr(srv, "FEED_PATH", str(tmp_path / "lobby_feed.jsonl"))
