"""Shared fixtures for the tuipet test suite.

The single most important thing this file does is **isolate persistence** so a
test can never touch Joel's real save/settings at ~/.local/share/tuipet/ (a
leaked test save has corrupted the live game before). The `isolate_save`
fixture is autouse, so every test in the suite gets a throwaway save dir.
"""
import pytest

from tuipet import persistence


@pytest.fixture(autouse=True)
def isolate_save(tmp_path, monkeypatch):
    """Redirect all persistence I/O into a per-test tmp dir.

    persistence resolves SAVE_PATH/SETTINGS_PATH at call time (`path or <GLOBAL>`),
    so monkeypatching the module globals is enough to fully sandbox it.
    """
    monkeypatch.setattr(persistence, "SAVE_DIR", str(tmp_path))
    monkeypatch.setattr(persistence, "SAVE_PATH", str(tmp_path / "save.json"))
    monkeypatch.setattr(persistence, "SETTINGS_PATH", str(tmp_path / "settings.json"))
    # module-level write-dedupe caches must not leak between sandboxes: a
    # num already in _ALBUM_SEEN makes album_add() a no-op on the FRESH save
    # (test_egg_guide caught it shadowing test_egg_economy, 2026-07-12)
    monkeypatch.setattr(persistence, "_ALBUM_SEEN", set())
    # sound's volume + wav-cache paths ride persistence.SAVE_DIR at call
    # time since the 2026-07-19 shape sweep -- the SAVE_DIR patch above
    # sandboxes them; only the in-memory volume needs resetting
    from tuipet import sound
    monkeypatch.setattr(sound, "_volume", sound.DEFAULT_VOLUME)
    yield


@pytest.fixture(autouse=True)
def weekday_bits(monkeypatch):
    """Pin weekend_bonus to a weekday (x1.0) so every bit-amount pin in the
    suite is deterministic no matter which real day it runs on. The weekend
    tests exercise _weekend_mult directly / re-patch weekend_bonus to 1.5."""
    from tuipet import pet as pet_mod
    monkeypatch.setattr(pet_mod, "weekend_bonus", lambda now=None: 1.0)
    yield


@pytest.fixture(autouse=True)
def ordinary_day(monkeypatch):
    """⭐PIN THE CALENDAR TO AN ORDINARY DAY, like weekday_bits pins the week.

    tuipet has four festival dates (tournament.HOLIDAYS: Jan 1, Aug 1, Oct 31,
    Dec 25) and a festival changes real behaviour all over the game -- 2x bits,
    richer road finds, and an ambient decor prop blitted into the ARENA
    OVERLAY.  Any test that asserts over the whole overlay, or pins a bit
    amount, therefore passed 361 days a year and failed on the other four.

    Caught the hard way on 2026-08-01 (Odaiba Memorial Day): 21 tests red on a
    clean tree, none of them touching the code under change.  A suite that is
    only green on most days is not a gate.

    Pinned at the DATE SOURCE (`tournament._today`, whose own docstring names
    it "one date source for the cadence layer (tests monkeypatch here)"), not
    at `holiday()`, so both existing escape hatches keep working: a test that
    re-patches `_today` (the cup cadence's `on_date`) overrides this, and a
    test that passes an explicit date to `holiday()`/`_holiday_decor()` was
    never going through here at all.

    2026-06-17 is a plain Wednesday in SUMMER -- the same season the suite ran
    in when this was written, so no cup pool moves under it."""
    import datetime
    from tuipet import tournament
    monkeypatch.setattr(tournament, "_today", lambda: datetime.date(2026, 6, 17))
    yield


def _by_num():
    from tuipet import data
    _, by_num = data.load_sprites()
    return by_num


def live_num(stage="Rookie"):
    """A real, non-placeholder Digimon num of the given stage, or None if assets
    aren't installed (sprites are gitignored / regenerated by setup_assets.sh)."""
    from tuipet import data
    by_num = _by_num()
    return next((n for n, r in by_num.items()
                 if r["stage"] == stage and not data.is_placeholder(n)), None)


@pytest.fixture
def live_pet():
    """A freshly-spawned Rookie from real sprite data (skips if assets missing)."""
    from tuipet.pet import Pet
    num = live_num("Rookie")
    if num is None:
        pytest.skip("sprite assets not installed (run tools/setup_assets.sh)")
    p = Pet.from_num(num)
    p.obedience = 500        # out-roll the canon item/food refusal (audit 2026-07)
    return p


# (the futon_item discovery helper left with the staple props:
# strict-DSprite items, 2026-07-17)


@pytest.fixture(autouse=True)
def _sandbox_lobby_feed(tmp_path, monkeypatch):
    """The lobby server module logs public events to FEED_PATH on login/chat/
    disconnect -- any test driving server flows must write a scratch feed, or
    pytest runs append real-looking events to the repo copy (leak found
    2026-07-10: test_bugreport/test_save_integrity grew server/lobby_feed.jsonl
    on every run)."""
    import os as _os
    import sys as _sys
    # import (not just look up) the module: the first test in a session that
    # imports server INSIDE its body used to run before this fixture had
    # anything to patch -- order-dependent sandboxing (test audit 2026-07-13)
    _sys.path.insert(0, _os.path.join(_os.path.dirname(__file__), "..", "server"))
    try:
        import server as srv
    except Exception:
        srv = None
    if srv is not None and hasattr(srv, "FEED_PATH"):
        monkeypatch.setattr(srv, "FEED_PATH", str(tmp_path / "lobby_feed.jsonl"))
    if srv is not None and hasattr(srv, "BUGS_PATH"):
        monkeypatch.setattr(srv, "BUGS_PATH", str(tmp_path / "bugs.jsonl"))
    if srv is not None and hasattr(srv, "LADDER_PATH"):
        monkeypatch.setattr(srv, "LADDER_PATH", str(tmp_path / "ladder.json"))
        monkeypatch.setattr(srv, "LADDER", {"seasons": {}, "claimed": {}})
        srv._ladder_pending.clear()
        srv._ladder_confirm.clear()
        srv._ladder_pair_hour.clear()

@pytest.fixture(autouse=True)
def never_run_pip(monkeypatch):
    """No test may install anything.  The launch auto-updater (2026-07-14) calls
    update.run_upgrade(), and a test that forgot to mock it REALLY RAN pip --
    it upgraded tuipet inside .venv-dev mid-suite.  Same doctrine as
    isolate_save: the suite can never touch the real thing.  A test that wants
    the success path monkeypatches run_upgrade itself; this only stops the real
    one.
    """
    from tuipet import update

    def _refuse(*_a, **_k):
        raise AssertionError(
            "a test tried to shell out to pip -- patch update._RUN "
            "(or mock run_upgrade/upgrade_argv) instead")

    monkeypatch.setattr(update, "_RUN", _refuse)


def road_card(pan):
    """The ROAD CARD's plain text for a live AdventurePanel (v0.5.327).

    The run's numbers — legs, lives, energy, bits, fights, loot, the chain —
    moved OFF the 40-cell strip and onto the status card when Joel ordered the
    strip thinned to just its keys (v0.5.328).  Tests that used to read them
    out of `pan.strip()` read them here."""
    import re
    from tuipet import statusbox

    class _Stats:
        def __init__(self):
            self.txt, self.border_subtitle = "", ""

        def update(self, t):
            self.txt = str(t)

    class _App:
        def __init__(self):
            self.pet, self.mode, self.stats_w = pan.pet, pan, _Stats()
            self.sound = False

    app = _App()
    statusbox.painter_for(pan)(app)
    return re.sub(r"\[/?[^\[\]]*\]", "", app.stats_w.txt)
