/*
 * Decompiled with CFR 0.152.
 */
package Model;

public class Enum {

    public static enum XAntibodyState {
        None,
        Temporary,
        Permanent,
        XProgram;

    }

    public static enum XAntibody {
        None,
        Natural,
        Induced;

    }

    public static enum SpecialEvolution {
        None,
        Jogress,
        Fusion,
        Xros,
        Mode,
        Failed,
        Death;

    }

    public static enum AIType {
        Random,
        Brute,
        StrategicBalanced,
        StrategicBrute,
        StrategicDefense;

    }

    public static enum AttackCondition {
        None,
        EnemyIsVaccine,
        EnemyIsData,
        EnemyIsVirus,
        PlayerIsVaccine,
        PlayerIsData,
        PlayerIsVirus,
        AttackVaccine,
        AttackData,
        AttackVirus,
        VaccineWeaker,
        DataWeaker,
        VirusWeaker,
        PlayerWeaker,
        VaccineStronger,
        DataStronger,
        VirusStronger,
        PlayerStronger,
        PlayerIsNSP,
        PlayerIsNS,
        PlayerIsDR,
        PlayerIsDS,
        PlayerIsWG,
        PlayerIsDA,
        PlayerIsNA,
        PlayerIsJT,
        PlayerIsME,
        PlayerIsVB,
        EnemyIsNSP,
        EnemyIsNS,
        EnemyIsDR,
        EnemyIsDS,
        EnemyIsWG,
        EnemyIsDA,
        EnemyIsNA,
        EnemyIsJT,
        EnemyIsME,
        EnemyIsVB,
        ForcePlayerSecond,
        PlayerFirst,
        PlayerSecond,
        SacrificeAttack,
        SacrificeDefense,
        SacrificeHealth,
        LowerPlayerHealth,
        HigherPlayerHealth,
        HalfPlayerHealth,
        HalfOppHealth,
        EffectTimesTwo,
        EffectTimesThree,
        ConditionsTimesTwo,
        ConditionsTimesThree;

    }

    public static enum AttackEffect {
        None,
        AttackUp,
        DefenseUp,
        Weaken,
        DisableAttack,
        DisableEffect,
        Counter,
        First,
        Second,
        Leech,
        Absorb,
        Heal,
        ForceOppVaccine,
        ForceOppData,
        ForceOppVirus,
        PlayerIsVaccine,
        PlayerIsData,
        PlayerIsVirus,
        EnemyIsVaccine,
        EnemyIsData,
        EnemyIsVirus,
        PlayerIsNSP,
        PlayerIsNS,
        PlayerIsDR,
        PlayerIsDS,
        PlayerIsWG,
        PlayerIsDA,
        PlayerIsNA,
        PlayerIsJT,
        PlayerIsME,
        PlayerIsVB,
        EnemyIsNSP,
        EnemyIsNS,
        EnemyIsDR,
        EnemyIsDS,
        EnemyIsWG,
        EnemyIsDA,
        EnemyIsNA,
        EnemyIsJT,
        EnemyIsME,
        EnemyIsVB,
        Empty;

    }

    public static enum Weather {
        Clear,
        Raining,
        Snowing,
        Cloudy,
        Drizzling,
        HeavyRain,
        LightSnow,
        HeavySnow;

    }

    public static enum Element {
        None,
        Fire,
        Light,
        Ice,
        Wind,
        Thunder,
        Earth,
        Water,
        Wood,
        Metal,
        Dark,
        NA;

    }

    public static enum Field {
        None,
        DragonsRoar,
        DeepSaver,
        JungleTrooper,
        MetalEmpire,
        NatureSpirit,
        WindGuardian,
        NightmareSoldier,
        DarkArea,
        VirusBuster,
        NA;

    }

    public static enum Condition {
        None,
        GreaterThan,
        LessThan,
        EqualTo;

    }

    public static enum Season {
        Spring,
        Summer,
        Fall,
        Winter,
        None;

    }

    public static enum Food {
        Meat,
        Fish,
        Fruit,
        Veg,
        Med,
        Junk,
        Grain,
        Dairy,
        None;

    }

    public static enum Mood {
        Happy,
        Neutral,
        Unhappy,
        Depressed,
        None;

    }

    public static enum Stage {
        Egg,
        Fresh,
        InTraining,
        Rookie,
        Champion,
        Ultimate,
        Mega,
        None;

    }

    public static enum Attribute {
        Vaccine,
        Data,
        Virus,
        None,
        NA;

    }

    public static enum Weight {
        Over,
        Healthy,
        Under,
        None;

    }

    public static enum State {
        None,
        Hatching,
        Idling,
        Eating,
        Munching,
        DisposeFood,
        Assistant_Feed,
        PoopDance,
        Pooping,
        Pooping_Outside_Move,
        Pooping_Outside,
        Pooping_Outside_Return,
        Cleaning,
        Assistant_Clean,
        Assistant_Lights,
        Evolving,
        Jogress,
        Dying,
        Dead,
        Cheering,
        Jeering,
        Sad_Jeering,
        Bad_Health_Jeering,
        Losing,
        Winning,
        Retreating,
        Bad_Praise,
        Bad_Scold,
        Refusing,
        Bandaging,
        Battle_Flash,
        Battle_Start,
        Jogress_Flash,
        Jogress_Start,
        WaitingTurn,
        Vaccine_Training,
        Data_Training,
        Virus_Training,
        HP_Training,
        HP_Training_AttackSuccess,
        HP_Training_AttackFail,
        Tourney_Start,
        NPC_Fight,
        Tourney_Trophy,
        Buying_Food,
        Buying_Habitat,
        Buying_Item,
        Selling_Food,
        Selling_Item,
        Battling_PlayerAttack,
        Battling_OpponentReceiveAttack,
        Battling_OpponentAttack,
        Battling_PlayerReceiveAttack,
        Battling_PlayerHit,
        Battling_OpponentHit,
        Battling_PlayerHit_Aftermath,
        Battling_OpponentHit_Aftermath,
        EnemyHealing,
        PlayerHealing,
        Attacking,
        Attack_Contact,
        Attack_Aftermath,
        BossDeath,
        ZoneChange,
        BossParade,
        MapComplete,
        Yawning,
        Weathering,
        Surprising,
        X_Program,
        X_AntibodyInc,
        Xros,
        ItemEvol,
        Reject,
        Play,
        PlayAngry,
        AngrySurprise,
        Bounce,
        Ride,
        Study,
        Interact,
        InteractAngry,
        InteractXylophone,
        InteractToyOven,
        InteractTelevision,
        InteractComputer,
        Jump,
        Lift,
        Bathe,
        Shower,
        Toilet,
        SelfToilet,
        PortToilet,
        SelfPortToilet,
        LifeInc,
        LifeDec,
        Retreat_Town,
        Teleport_Leave,
        Teleport_Arrive,
        Recover,
        BirdraTransport,
        PhoenixTransport,
        GarudaTransport,
        WhaTransport,
        WhaTransportFade,
        WhaTransportSwim,
        WhaTransportArrive,
        FadeOut,
        FadeIn,
        TransportFall,
        UnlockItem,
        UnlockInheritance,
        UnlockFood,
        UnlockDNA,
        Inherit,
        DNA_Generate,
        HealthInc,
        PerfectWinsInc,
        Pausing,
        Unpausing,
        Gifting,
        GiftCall,
        Discovering,
        ReturnItem,
        DiscoverEnemy,
        DiscoverCall,
        Requesting,
        RequestCall,
        TournamentAlert,
        EarningBits,
        EarningBits_Tourney,
        DNA_Feeding,
        EvolSilhouetteTransition,
        EvolSilhouetteBack,
        Personality_Happy,
        Personality_Angry,
        Tantrum,
        NormalMorning,
        GoodMorning,
        BadMorning,
        TerribleMorning,
        Birthday_Good,
        Birthday_Bad,
        Birthday_Normal;

    }

    public static enum Personality {
        Docile,
        Gluttonous,
        Restless,
        Content,
        Calm,
        Hasty,
        Lazy,
        Fidgety,
        Stoic,
        Cheerful,
        Eager,
        Hyper,
        Generous,
        Carefree,
        Playful,
        Loafing,
        Antsy,
        Mellow,
        Serious,
        Selfish,
        Anxious,
        Tolerant,
        Apathetic,
        Impish,
        Lethargic,
        Unruly,
        Callous,
        None;

    }

    public static enum Time {
        Morning,
        Noon,
        Night,
        None;

    }

    public static enum Menu {
        None,
        Loading,
        Start,
        Set_EggClock,
        Save_Name,
        Load_Name,
        SetDifficulty,
        Restart,
        Choose_Egg,
        Save_Validation,
        SaveExit_Validation,
        Clock_Validation,
        Battle_Validation,
        Battle_VS,
        Multi_Validation_Battle,
        Multi_Validation_Jogress,
        Host_Name_Battle,
        Host_Name_Jogress,
        Host_Port_Battle,
        Host_Port_Jogress,
        ConnectError_Jogress,
        ConnectError_Battle,
        Jogress_Mismatch,
        Battle_Style,
        Attack_Validation,
        AttackType_Validation,
        UseCard_Validation,
        Surrender_Validation,
        Attack_Description,
        EnemyAttack_Description,
        Enemy_Attacks,
        Training_Select,
        Training_Action_Red,
        Training_Action_Green,
        Training_Action_Yellow,
        Food_Buy_Sell_Validation,
        Item_Buy_Sell_Validation,
        Feed_Validation,
        Food_Inventory,
        Food_Inventory_Sell,
        Food_Shop,
        Use_Food,
        Buy_Food,
        Sell_Food,
        Medical,
        Food_Purchase,
        Habitat_Purchase,
        Item_Purchase,
        Food_Sale,
        Item_Sale,
        PraiseScold_Validation,
        DigiMemory_Validation,
        Shop_Validation,
        Inventory_Validation,
        Item_Inventory,
        Item_Inventory_Sell,
        Item_Shop,
        Use_Item,
        Buy_Item,
        Sell_Item,
        Use_Med_Food,
        Use_Med_Item,
        Habitat_Shop,
        Habitat_Inventory,
        Habitat_Description,
        Habitat_Compatibility,
        Habitat_Incompatibility,
        Habitat_Shop_Description,
        Habitat_Shop_Compatibility,
        Habitat_Shop_Incompatibility,
        Data_Clock,
        Data_Status,
        Data_Power,
        Data_HP,
        Data_Person,
        Data_Person_Detail,
        Data_Likes,
        Data_Dislikes,
        Data_SpeciesLikes,
        Data_SpeciesDislikes,
        Data_Intolerant,
        Data_Hunger,
        Data_Strength,
        Data_HealthTrack,
        Data_Energy,
        Data_Battles,
        Data_Temp,
        Data_Nutrition,
        Data_Calories,
        Food_Calories,
        Data_BattleLevels,
        Buy_Nutrition,
        Sell_Nutrition,
        Use_Nutrition,
        Med_Nutrition,
        Set_Clock,
        Set_AutoCare,
        EvolutionTree,
        Tourney_Options,
        Season_Records,
        Spring_Records,
        Summer_Records,
        Fall_Records,
        Winter_Records,
        Tourney_Enter,
        Tourney_Registration,
        Registration_Prelim_Details,
        Records_Prelim_Details,
        Tourney_Validation,
        TrophyDetails,
        Tourney_Surrender,
        Roster,
        Royale_Lineup,
        TrophyPrizeBits,
        TrophyPrizeItem,
        Card_Options,
        Cards,
        Card_Shop,
        WorldMapSelect,
        WorldMapSelect_Ticket,
        MapZoneSelect,
        ChooseZone,
        Map_Validation,
        Map_Validation_Ticket,
        Steps,
        Zone_Validation,
        Zone_Validation_Ticket,
        ZoneDetail,
        Settings,
        Settings_Validation,
        Investigate_Validation,
        EvolutionMenu,
        EvolutionInventory,
        UseEvolutionItem,
        EvolutionState,
        EvolSilhouette,
        DNA_Validation,
        DNA_Inventory,
        DNA_Stats,
        DNA_GenerateValidate,
        DNA_Detail;

    }
}

